version: "3.9"

services:
  web:
    build:
      context: web/app
      args:
        # These env variables used in next.config.js can only be set during build.
        # But since you can't access the running api at this URL while building,
        # SSG at build time is not usable in Next.js 
        - API_URL=http://api:3000
        - MATOMO_URL=${MATOMO_URL:?Matomo URL}
        - MATOMO_SITE_ID=${MATOMO_SITE_ID:?Matomo site ID}
      network: host
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - "${WEB_PORT:?Web server port}:3000"

networks:
  backend:
  frontend:
