services:
  web:
    build:
      context: web/app
      args:
        - API_URL=http://backend:8000
    restart: unless-stopped
    networks:
      - frontend
    volumes:
      - ./web/app/public/graphs:/app/public/graphs:ro
    ports:
      - "${WEB_PORT:?Web server port}:3000"

  backend:
    build:
      context: ./backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - ./data/parquets:/app/data/parquets
      - ./data/precomputed:/app/models:ro
      - ./web/app/public/graphs:/app/public/graphs
    networks:
      - frontend

networks:
  frontend:
